# Install pre-commit hooks via:
# pre-commit install
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
      exclude: &exclude_txtfiles >-
        (?x)^(
            tests/.*.*out|
            tests/.*.in|
            examples/.*.xsf|
            docs/.*.agr|
            docs/.*.xsf
        )$
    - id: mixed-line-ending
    - id: trailing-whitespace
      exclude: *exclude_txtfiles
    - id: check-json

- repo: https://github.com/asottile/pyupgrade
  rev: v3.13.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      additional_dependencies: ["toml"]

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black

- repo: local
  hooks:
  - id: pylint
    language: system
    types: [file, python]
    name: pylint
    description: "This hook runs the pylint static code analyzer"
    exclude: &exclude_files >
      (?x)^(
          docs/.*|
      )$
    entry: pylint
